global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
  
  # Target is set to the host machine's localhost
  - job_name: "grpc"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9091"]